### ISSUE TITLE
RFC3164 Support

### ISSUE THREAD

**Issue by recklessop** [pierredavidbelanger/raftman#1]
Is there support for BSD style Syslog? maybe I missed how to configure for that version of clients.

Thanks!

**Comment by pierredavidbelanger** [comment]
Thank you for your interest in this project! You should have said "first" ;)

I am sorry, there is not much doc about how to configure this tool, but `RFC3164` is indeed supported (have a look [here](https://github.com/pierredavidbelanger/raftman/blob/6a8f36a6af8b64211ce3e463c5c251258b9f41cc/frontend/syslog.go#L116) to see witch "part" of the `RFC3164` Raftman is using)

This is not the default , so you need to use [raftman CLI args](https://github.com/pierredavidbelanger/raftman#configuration) to enable it, for example like this:
```
raftman -frontend syslog+udp://:514?format=RFC3164
```
